# Generated by Django 5.2.12 on 2026-03-18 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryExemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subdivision', models.CharField(help_text='e.g. 1-210(b)(5)(A)', max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('statutory_text', models.TextField()),
                ('citation', models.CharField(max_length=255)),
                ('guidance_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Statutory Exemption',
                'verbose_name_plural': 'Statutory Exemptions',
                'ordering': ['subdivision'],
            },
        ),
        migrations.CreateModel(
            name='FOIARequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('scope_defined', 'Scope Defined'), ('searching', 'Searching'), ('under_review', 'Under Review'), ('package_ready', 'Package Ready'), ('senior_review', 'Senior Review'), ('responded', 'Responded'), ('appealed', 'Appealed'), ('closed', 'Closed')], default='received', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('requester_phone', models.CharField(blank=True, max_length=20)),
                ('requester_organization', models.CharField(blank=True, max_length=255)),
                ('requester_address', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('original_request_text', models.TextField(blank=True)),
                ('date_received', models.DateField()),
                ('statutory_deadline', models.DateField(blank=True, help_text='4 business days from receipt per CT FOIA', null=True)),
                ('extended_deadline', models.DateField(blank=True, null=True)),
                ('date_responded', models.DateField(blank=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_foia_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_foia_requests', to=settings.AUTH_USER_MODEL)),
                ('related_companies', models.ManyToManyField(blank=True, related_name='foia_requests', to='companies.company')),
                ('reviewing_attorney', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing_foia_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FOIA Request',
                'verbose_name_plural': 'FOIA Requests',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='FOIAAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appeal_status', models.CharField(choices=[('filed', 'Filed'), ('hearing_scheduled', 'Hearing Scheduled'), ('hearing_completed', 'Hearing Completed'), ('decision_pending', 'Decision Pending'), ('upheld', 'Upheld (Agency Decision Stands)'), ('overturned', 'Overturned'), ('settled', 'Settled'), ('withdrawn', 'Withdrawn')], default='filed', max_length=25)),
                ('appeal_number', models.CharField(blank=True, max_length=50)),
                ('filed_date', models.DateField()),
                ('appellant_arguments', models.TextField(blank=True)),
                ('agency_response', models.TextField(blank=True)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('hearing_notes', models.TextField(blank=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('decision_summary', models.TextField(blank=True)),
                ('decision_document', models.FileField(blank=True, upload_to='foia_appeals/%Y/%m/')),
                ('lessons_learned', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foia_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='foia.foiarequest')),
            ],
            options={
                'verbose_name': 'FOIA Appeal',
                'verbose_name_plural': 'FOIA Appeals',
                'ordering': ['-filed_date'],
            },
        ),
        migrations.CreateModel(
            name='FOIAResponsePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.FileField(blank=True, upload_to='foia_responses/%Y/%m/')),
                ('response_file', models.FileField(blank=True, upload_to='foia_responses/%Y/%m/')),
                ('privilege_log', models.FileField(blank=True, upload_to='foia_responses/%Y/%m/')),
                ('total_records_found', models.PositiveIntegerField(default=0)),
                ('records_released', models.PositiveIntegerField(default=0)),
                ('records_withheld', models.PositiveIntegerField(default=0)),
                ('records_partially_released', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_reviewed_by_attorney', models.BooleanField(default=False)),
                ('is_approved_by_senior', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foia_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_package', to='foia.foiarequest')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FOIA Response Package',
                'verbose_name_plural': 'FOIA Response Packages',
            },
        ),
        migrations.CreateModel(
            name='FOIAScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Search keywords')),
                ('company_names', models.JSONField(blank=True, default=list, help_text='Company names to search')),
                ('contact_names', models.JSONField(blank=True, default=list, help_text='Contact names to search')),
                ('record_types', models.JSONField(blank=True, default=list, help_text='Types of records to search (notes, interactions, etc.)')),
                ('scope_notes', models.TextField(blank=True)),
                ('defined_at', models.DateTimeField(auto_now_add=True)),
                ('defined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('foia_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='foia.foiarequest')),
            ],
            options={
                'verbose_name': 'FOIA Scope',
                'verbose_name_plural': 'FOIA Scopes',
            },
        ),
        migrations.CreateModel(
            name='FOIASearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(help_text='e.g. note, interaction, document', max_length=50)),
                ('record_id', models.UUIDField()),
                ('record_description', models.TextField(blank=True)),
                ('snapshot_content', models.TextField(blank=True)),
                ('snapshot_metadata', models.JSONField(blank=True, default=dict)),
                ('snapshot_taken_at', models.DateTimeField(auto_now_add=True)),
                ('pre_classification', models.CharField(choices=[('likely_responsive', 'Likely Responsive'), ('likely_exempt', 'Likely Exempt'), ('needs_review', 'Needs Review'), ('not_relevant', 'Not Relevant')], default='needs_review', max_length=20)),
                ('classification_reason', models.TextField(blank=True)),
                ('foia_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='foia.foiarequest')),
            ],
            options={
                'verbose_name': 'FOIA Search Result',
                'verbose_name_plural': 'FOIA Search Results',
                'ordering': ['record_type', 'snapshot_taken_at'],
            },
        ),
        migrations.CreateModel(
            name='FOIADetermination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('release', 'Release'), ('withhold', 'Withhold'), ('partial_release', 'Partial Release'), ('refer', 'Refer to Another Agency')], max_length=20)),
                ('exemption_review', models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='not_reviewed', max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('redacted_content', models.TextField(blank=True)),
                ('attorney_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foia_determinations', to=settings.AUTH_USER_MODEL)),
                ('search_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='determination', to='foia.foiasearchresult')),
                ('exemptions_claimed', models.ManyToManyField(blank=True, related_name='determinations', to='foia.statutoryexemption')),
            ],
            options={
                'verbose_name': 'FOIA Determination',
                'verbose_name_plural': 'FOIA Determinations',
            },
        ),
        migrations.AddIndex(
            model_name='foiarequest',
            index=models.Index(fields=['status'], name='idx_foia_status'),
        ),
        migrations.AddIndex(
            model_name='foiarequest',
            index=models.Index(fields=['statutory_deadline'], name='idx_foia_deadline'),
        ),
        migrations.AddIndex(
            model_name='foiarequest',
            index=models.Index(fields=['request_number'], name='idx_foia_number'),
        ),
    ]
