# Generated by Django 5.2.12 on 2026-03-20 02:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FOIADocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Extracted text content for full-text search')),
                ('file', models.FileField(blank=True, upload_to='foia_documents/%Y/%m/')),
                ('document_date', models.DateField(blank=True, help_text='Date of the original document', null=True)),
                ('source', models.CharField(blank=True, help_text='Where this document came from (e.g. department, system)', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foia_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FOIA Document',
                'verbose_name_plural': 'FOIA Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
